name: Windows
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure
      run: cmake -S . -B build -DRPP_TEST=ON
    - name: Build
      run: cmake --build build --config Release
