name: Windows
on: [push]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure
      run: cmake -S . -B build -DRPP_TEST=ON
    - name: Build
      run: cmake --build build --config Release
